change flags again, improve output

diff --git a/mulle-objc-clone b/mulle-objc-clone
--- a/mulle-objc-clone
+++ b/mulle-objc-clone
@@ -41,12 +41,12 @@ usage: mulle-xcode-clone [options]
 
    Options
       -a   : don't ask
-      -b   : branch to checkout for all (default: release)
-      -cb  : branch to checkout for C libraries (inherits -b)
-      -eb  : branch to checkout for embedded libraries (inherits -cb)
-      -h   : host to checkout from for all (default: https://github.com/mulle-objc/)
-      -ch  : host to checkout from for C libraries (inherits -h)
-      -eh  : host to checkout from for embedded libraries (inherits -ch)
+      -b   : branch to checkout (default: release)
+      -cb  : branch to checkout for C repositories (inherits -b)
+      -eb  : branch to checkout for embedded repositories (inherits -cb)
+      -p   : prefix for repositories (default: https://github.com/mulle-objc/)
+      -cp  : prefix for C repositories (inherits -p)
+      -ep  : prefix for embedded repositories (inherits -cp)
 EOF
    exit 1
 }
@@ -77,33 +77,33 @@ do
          OBJC_BRANCH="$1"
       ;;
 
-      -cb|--common-branch)
+      -cb|--c-branch)
          shift
-         [ $# -eq 0 ] && echo "branch missing" >&2 && exit 1
+         [ $# -eq 0 ] && echo "c branch missing" >&2 && exit 1
          COMMON_BRANCH="$1"
       ;;
 
       -eb|--embedded-branch)
          shift
-         [ $# -eq 0 ] && echo "branch missing" >&2 && exit 1
+         [ $# -eq 0 ] && echo "embedded branch missing" >&2 && exit 1
          EMBEDDED_BRANCH="$1"
       ;;
 
-      -h|--host|-oh|--objc-host)
+      -p|--repository-prefix|-op|--objc-repository-prefix)
          shift
-         [ $# -eq 0 ] && echo "host directory missing" >&2 && exit 1
+         [ $# -eq 0 ] && echo "repository prefix missing" >&2 && exit 1
          OBJC_REPOPREFIX="$1"
       ;;
 
-      -ch|--common-host)
+      -cp|--c-repository-prefix)
          shift
-         [ $# -eq 0 ] && echo "host directory missing" >&2 && exit 1
+         [ $# -eq 0 ] && echo "c repository prefix missing" >&2 && exit 1
          COMMON_REPOPREFIX="$1"
       ;;
 
-      -eh|--embedded-host)
+      -ep|-embedded-repository-prefix)
          shift
-         [ $# -eq 0 ] && echo "host directory missing" >&2 && exit 1
+         [ $# -eq 0 ] && echo "embeddes repository prefix missing" >&2 && exit 1
          EMBEDDED_REPOPREFIX="$1"
       ;;
 
@@ -243,7 +243,7 @@ blurb_and_ask()
    do
       echo "The branch \"${EMBEDDED_BRANCH}\" of \"${repo}\" from \"${EMBEDDED_REPOPREFIX}\" will be cloned into \"${MASTER_DIR}\"."
    done
- 
+
    cat <<EOF
 
 Then everything will be set up in a convenient way using mulle-bootstrap.
@@ -347,6 +347,7 @@ clone()
          fi
       done
 
+      local  last_repos
 
       for i in $OBJC_REPOS
       do
@@ -357,6 +358,7 @@ clone()
          else
             echo "${i} already exists, skipping..." >&2
          fi
+         last_repos="$i"
       done
 
       for i in $REPOS
@@ -383,9 +385,17 @@ clone()
       mulle-bootstrap config -y symlinks
 
       # or what ?
-      mulle-bootstrap config override_branch "${EMBEDDED_BRANCH}"
-      mulle-bootstrap
-   )
+      # åmulle-bootstrap config override_branch "${EMBEDDED_BRANCH}"
+      mulle-bootstrap || exit 1
+
+      cat <<EOF
+${last_repos} is now ready to be built with:
+
+cd '${MASTER_DIR}/${last_repos}'
+mulle-build
+EOF
+
+   ) || exit 1
 }
 
 
@@ -421,7 +431,7 @@ main()
       build)
          local final
 
-         final="`echo "${REPOS}" | tail -1 `"
+         final="`echo "${OBJC_REPOS}" | tail -1 `"
          (
             cd "${MASTER_DIR}/${final}" || exit 1
             mulle-build "$@"  || exit 1
